package com.github.pablomathdev.presentation.v1.exception;

public enum ErrorType {

	BODY_REQUEST_SINTAX_ERROR,
	RESOURCE_NOT_FOUND,
	RESOURCE_ALREADY_EXISTS,
	INVALID_PARAM,
	RESOURCE_INTEGRITY_VIOLATION,
	SERVER_ERROR,
	INVALID_ARGUMENT
	
}
